### ISSUE TITLE
fragmented set and get req don't work =^(

### ISSUE THREAD

**Issue by kistenklaus** [mu-zero-HYPERLOOP/canzero#141]

**Comment by kistenklaus** [comment]
This works
```
error_level_config:
  info_thresh : d32<-10000..10000>
  info_timeout: d32<0..60>
  warning_thresh: d32<-10000..10000>
  warning_timeout: d32<0..60>
  error_thresh: d32<-10000..10000>
  error_timeout: d32<0..60>
  ignore_info: bool_t
  ignore_warning: bool_t
  ignore_error: bool_t
```
this doesn't 
```
error_level_config:
  ignore_info: bool_t
  ignore_warning: bool_t
  ignore_error: bool_t
  info_thresh : d32<-10000..10000>
  info_timeout: d32<0..60>
  warning_thresh: d32<-10000..10000>
  warning_timeout: d32<0..60>
  error_thresh: d32<-10000..10000>
  error_timeout: d32<0..60>

```
